[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phiesta"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "rasterio",
    "tifffile",
    "requests",
    "termcolor",
    "InsulaWorkflowClient",
    "pyproj",
]


[tool.setuptools.packages.find]
include = ["phiesta", "phiesta.*", "third_party", "third_party.*"]

[tool.setuptools.package-data]
third_party = ["phisat2_exec/*.bin"]

[project.optional-dependencies]
triplets = [
    "opencv-python",
    "torch",
    "pyproj",
    "scipy",
    "scikit-image",
    "geopandas",
    "sentinelhub",
    "eo-learn",
    "sunpy",
]
docs = [
    "sphinx",
]